### ISSUE TITLE
Exception 'threading violation: expected the main thread' was thrown while invoking setBrightness on target ScreenBrightness with params (     "0.8",     4186,     4187 )

### ISSUE THREAD

**Issue by NikitaNeganov** [robinpowered/react-native-screen-brightness#35]
Xcode 11
MacOS 10.14.6 (18G95
Simulator iPhone X 13.0
iPhone 6s 13.1.2

Any attempt to `setBrighntess` to a higher value than 0.5 results in the following error

```
Exception 'threading violation: expected the main thread' was thrown while invoking setBrightness on target ScreenBrightness with params (
    "0.55",
    3706,
    3707
)
callstack: (
	0   CoreFoundation                      0x00007fff23b98bde __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff503b5b20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23b98958 +[NSException raise:format:arguments:] + 88
	3   Foundation                          0x00007fff255eb6f5 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
	4   FrontBoardServices                  0x00007fff363306d7 -[FBSSerialQueue assertOnQueue] + 236
	5   FrontBoardServices                  0x00007fff362e00d7 -[FBSSceneImpl updateClientSettings:withTransitionContext:] + 71
	6   FrontBoardServices                  0x00007fff362e03be -[FBSSceneImpl updateClientSettingsWithTransitionBlock:] + 154
	7   FrontBoardServices                  0x00007fff362e02e3 -[FBSSceneImpl updateClientSettingsWithBlock:] + 110
	8   UIKitCore                           0x00007fff46cbe390 -[FBSScene(UIApp) updateUIClientSettingsWithBlock:] + 160
	9   UIKitCore                           0x00007fff46db7f80 -[UIDevice _setBacklightLevel:] + 152
	10  UIKitCore                           0x00007fff46dc2bb4 -[UIScreen setBrightness:] + 396
	11  quancy                              0x00000001041dadb6 -[ScreenBrightness brightnessLevel:setSystemBrightnessResolver:setSystemBrightnessRejector:] + 134
	12  CoreFoundation                      0x00007fff23b9f95c __invoking___ + 140
	13  CoreFoundation                      0x00007fff23b9cd8f -[NSInvocation invoke] + 287
	14  CoreFoundation                      0x00007fff23b9d1f4 -[NSInvocation invokeWithTarget:] + 68
	15  quancy                              0x0000000103df63f2 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 2658
	16  quancy                              0x0000000103e90317 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 791
	17  quancy                              0x0000000103e8fe23 _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 131
	18  quancy                              0x0000000103e8fd99 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 25
	19  libdispatch.dylib                   0x00007fff511fb888 _dispatch_call_block_and_release + 12
	20  libdispatch.dylib                   0x00007fff511fc7f9 _dispatch_client_callout + 8
	21  libdispatch.dylib                   0x00007fff51202566 _dispatch_lane_serial_drain + 707
	22  libdispatch.dylib                   0x00007fff51202f9c _dispatch_lane_invoke + 388
	23  libdispatch.dylib                   0x00007fff5120d06c _dispatch_workloop_worker_thread + 626
	24  libsystem_pthread.dylib             0x00007fff5141c611 _pthread_wqthread + 421
	25  libsystem_pthread.dylib             0x00007fff5141c3fd start_wqthread + 13
)
```

**Comment by makeitsimplehk** [comment]
I have tired simulator iPhone 6s 13.1,  simulator iPhone X 13.1 , simulator iPhone 11 with the same issue.

**Comment by makeitsimplehk** [comment]
After I edit

dispatch_sync(dispatch_get_main_queue(), ^{
        [UIScreen mainScreen].brightness = brightnessLevel;
});

in ScreenBrightness.m which is working now.

**Comment by NikitaNeganov** [comment]
@makeitsimplehk where exactly did you edit those?

There is no

```
dispatch_sync(dispatch_get_main_queue(), ^{
```

**Comment by makeitsimplehk** [comment]
in ScreenBrightness.m

- [UIScreen mainScreen].brightness = brightnessLevel;
+ dispatch_sync(dispatch_get_main_queue(), ^{
+    [UIScreen mainScreen].brightness = brightnessLevel;
+ });

**Comment by makeitsimplehk** [comment]
in ScreenBrightness.m

```
- [[UIScreen mainScreen] setBrightness:brightnessLevel];
+ dispatch_sync(dispatch_get_main_queue(), ^{
+    [UIScreen mainScreen].brightness = brightnessLevel;
+ });
```

**Comment by clevertree** [comment]
this needs a patch. editing files in node_modules folders is <_____________________>

**Comment by NikitaNeganov** [comment]
@clevertree I'm waiting for maintainers to notice the issue, though I temporarily forked and fixed this via @makeitsimplehk comment

**Comment by clevertree** [comment]
The fix worked for me too. Thanks again!

**Comment by christophermark** [comment]
Hello @clevertree, @makeitsimplehk, @NikitaNeganov!

Looks like there was a long-open PR (#28) that was overdue for a merge and will solve your problem.
I've merged it up and cut a release, `1.0.1` that should fix things for you.

Hope it fixes the issues you were having 🙂

**Comment by konstantinmv** [comment]
Still having the same error. 
Have updated the package to `1.0.1` and tried the fix and getting the sam error as @NikitaNeganov 
Anyone else?

**Comment by clevertree** [comment]
Switch your library with
https://github.com/c19354837/react-native-system-setting
use setAppBrightness() for the easiest fix.

-Ari
